workflow
Signed-off-by: Anas Nashif <anas.nashif@intel.com>

diff --git a/.github/workflows/assigner-workflow.yml b/.github/workflows/assigner-workflow.yml
--- a/.github/workflows/assigner-workflow.yml
+++ b/.github/workflows/assigner-workflow.yml
@@ -20,27 +20,38 @@ jobs:
       github.event.workflow_run.conclusion == 'success'
 
     steps:
-      - name: 'Download artifact'
-        uses: actions/github-script@v8.0.0 # v8.0.0
+      - name: Download artifacts
+        id: download-artifacts
+        uses: dawidd6/action-download-artifact@ac66b43f0e6a346234dd65d4d0c8fbb31cb316e5 # v11
+        with:
+          workflow: doc-build.yml
+          run_id: ${{ github.event.workflow_run.id }}
+          if_no_artifact_found: ignore
+
+      - name: Load PR number
+        if: steps.download-artifacts.outputs.found_artifact == 'true'
+        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
         with:
           script: |
-            var artifacts = await github.actions.listWorkflowRunArtifacts({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              run_id: ${{github.event.workflow_run.id }},
-            });
-            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
-              return artifact.name == "pr"
-            })[0];
-            var download = await github.actions.downloadArtifact({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              artifact_id: matchArtifact.id,
-              archive_format: 'zip',
-            });
-            var fs = require('fs');
-            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));
-      - run: unzip pr.zip
+            let fs = require("fs");
+            let pr_number = Number(fs.readFileSync("./NR"));
+            core.exportVariable("PR_NUM", pr_number);
+
+      - name: Check PR number
+        if: steps.download-artifacts.outputs.found_artifact == 'true'
+        id: check-pr
+        uses: carpentries/actions/check-valid-pr@2e20fd5ee53b691e27455ce7ca3b16ea885140e8 # v0.15.0
+        with:
+          pr: ${{ env.PR_NUM }}
+          sha: ${{ github.event.workflow_run.head_sha }}
+
+      - name: Validate PR number
+        if: |
+          steps.download-artifacts.outputs.found_artifact == 'true' &&
+          steps.check-pr.outputs.VALID != 'true'
+        run: |
+          echo "ABORT: PR number validation failed!"
+          exit 1
 
       - name: Check out source code
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
